### ISSUE TITLE
Ctrl+` on 1.16-merged-official crashes

### ISSUE THREAD

**Issue by AterAnimAvis** [AterAnimAvis/BlockRenderer#11]
```
java.lang.NullPointerException: Rendering screen
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:472) ~[forge-1.16.3-34.1.25_mapped_official_1.16.3-recomp.jar:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:436) ~[forge-1.16.3-34.1.25_mapped_official_1.16.3-recomp.jar:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.GuiUtils.drawHoveringText(GuiUtils.java:411) ~[forge-1.16.3-34.1.25_mapped_official_1.16.3-recomp.jar:?] {re:classloading}
	at com.unascribed.blockrenderer.forge.client.varia.rendering.Display.renderTooltip(Display.java:49) ~[main/:?] {re:classloading}
	at com.unascribed.blockrenderer.forge.client.screens.widgets.ItemButtonWidget.renderToolTip(ItemButtonWidget.java:89) ~[main/:?] {re:classloading}
	at com.unascribed.blockrenderer.forge.client.screens.widgets.ItemButtonWidget.renderButton(ItemButtonWidget.java:52) ~[main/:?] {re:classloading}
	at net.minecraft.client.gui.widget.Widget.render(Widget.java:79) ~[forge-1.16.3-34.1.25_mapped_official_1.16.3-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.render(Screen.java:76) ~[forge-1.16.3-34.1.25_mapped_official_1.16.3-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.unascribed.blockrenderer.forge.client.screens.SelectionScreen.render(SelectionScreen.java:87) ~[main/:?] 
```

**Comment by AterAnimAvis** [comment]
Introduced in 63166bce075cf9690a7ebf7f4b4521f7e463e76e
`client.font` is null at the point of ClassLoad - Only effects Forge
